version: '3'

services:

  server:
    image: gnerd/python-dev-box:latest
    # command: gunicorn -b 0.0.0.0:8000 todosapp.wsgi:application
    depends_on:
      - postgres
    volumes:
      - ./app:/app
      - ./shared:/host
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://pguser@postgres/database
    stdin_open: true
    tty: true

  postgres:
    image: postgres:9.6.2-alpine
    ports:
      - 54321:5432
    environment:
      POSTGRES_USER: pguser
      POSTGRES_DB: database